### ISSUE TITLE
Broke all the samplers

### ISSUE THREAD

**Issue by Krek12** [hnmr293/sd-webui-timemachine#1]
![Снимок экрана 2024-03-15 180311](https://github.com/hnmr293/sd-webui-timemachine/assets/134212972/2b28414f-0103-4729-9dc5-122735116720)
SamplerData(name='DPM++ 2M Karras test', constructor=<function add_dpmpp_2m_test.<locals>.constructor at 0x7f04137adf30>, aliases=['k_dpmpp_2m_ka_test'], options={'scheduler': 'karras'})

**AssertionError: bad sampler name: SamplerData(name='Euler a', constructor=<function <listcomp>.<lambda> at 0x7f042200a8c0>, aliases=['k_euler_a', 'k_euler_ancestral'], options={'uses_ensd': True})**

*** Error completing request
*** Arguments: ('task(2gzrxlchlimg25s)', '', '', [], 20, "SamplerData(name='DPM++ 2M Karras test', constructor=<function add_dpmpp_2m_test.<locals>.constructor at 0x7f04137adf30>, aliases=['k_dpmpp_2m_ka_test'], options={'scheduler': 'karras'})", 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x7f0437ec0be0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, '', 'from modules.processing import process_images\n\np.width = 768\np.height = 768\np.batch_size = 2\np.steps = 10\n\nreturn process_images(p)', 2, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "/home/studio-lab-user/asd/modules/call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "/home/studio-lab-user/asd/modules/call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "/home/studio-lab-user/asd/modules/txt2img.py", line 55, in txt2img
        processed = processing.process_images(p)
      File "/home/studio-lab-user/asd/modules/processing.py", line 732, in process_images
        res = process_images_inner(p)
      File "/home/studio-lab-user/asd/modules/processing.py", line 867, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "/home/studio-lab-user/asd/modules/processing.py", line 1137, in sample
        self.sampler = sd_samplers.create_sampler(self.sampler_name, self.sd_model)
      File "/home/studio-lab-user/asd/modules/sd_samplers.py", line 30, in create_sampler
        assert config is not None, f'bad sampler name: {name}'
    AssertionError: bad sampler name: SamplerData(name='DPM++ 2M Karras test', constructor=<function add_dpmpp_2m_test.<locals>.constructor at 0x7f04137adf30>, aliases=['k_dpmpp_2m_ka_test'], options={'scheduler': 'karras'})

---

**Comment by Krek12** [comment]
added the extension and now all samplers don't work as well as the extension button what did I do wrong?
![Снимок экрана 2024-03-15 180153](https://github.com/hnmr293/sd-webui-timemachine/assets/134212972/0233e4a0-9abe-4210-9ba9-c5c88a4eeb78)
